/**
 * IPC 通道名常量 — 类型安全的通道定义
 * 命名规范: {module}:{action}:{detail?}
 */
export const IPC_CHANNELS = {
  // 窗口管理
  WINDOW_OPEN: 'window:open',
  WINDOW_CLOSE: 'window:close',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_LIST: 'window:list',

  // 配置
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_GET_ALL: 'config:getAll',
  CONFIG_RESET: 'config:reset',
  CONFIG_EXPORT: 'config:export',
  CONFIG_IMPORT: 'config:import',

  // 功能包
  FEATURE_PACKAGE_LIST: 'feature:list',
  FEATURE_PACKAGE_INSTALL: 'feature:install',

  // 日志
  LOG_WRITE: 'log:write',
  LOG_EXPORT: 'log:export',

  // 数据库（预留 — 尚未实现，请勿在渲染进程调用）
  // DB_QUERY: 'db:query',
  // DB_RUN: 'db:run',

  // 自动化任务
  TASK_START: 'task:start',
  TASK_PAUSE: 'task:pause',
  TASK_RESUME: 'task:resume',
  TASK_STOP: 'task:stop',
  TASK_LIST: 'task:list',
  TASK_GET: 'task:get',
  TASK_SAVE: 'task:save',
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',
  TASK_DETAIL: 'task:detail',
  TASK_CLONE: 'task:clone',
  TASK_STATUS_CHANGED: 'task:statusChanged',
  TASK_BATCH_LIST: 'batch:list',
  TASK_BATCH_DETAIL: 'batch:detail',
  BATCH_RETRY: 'batch:retry',
  SCHEDULER_STATUS: 'scheduler:status',
  SIGNIN_TASK_SAVE: 'signin:task:save',
  SIGNIN_TASK_GET: 'signin:task:get',
  SIGNIN_TASK_RUN_NOW: 'signin:task:runNow',
  SIGNIN_TASK_INTERVENTION_RETRY: 'signin:task:interventionRetry',
  SIGNIN_TASK_STATUS: 'signin:task:status',
  SIGNIN_TASK_HISTORY: 'signin:task:history',
  SIGNIN_TASK_LOGIN_CAPTURE: 'signin:task:loginCapture',
  SIGNIN_NOTIFICATION_TEST_EMAIL: 'signin:notification:testEmail',

  // 任务运营中台：工作区 / 协作
  WORKSPACE_LIST: 'workspace:list',
  WORKSPACE_CREATE: 'workspace:create',
  WORKSPACE_UPDATE: 'workspace:update',
  WORKSPACE_DUTY_GET: 'workspace:duty:get',
  WORKSPACE_DUTY_SHIFT_LIST: 'workspace:duty:shift:list',
  WORKSPACE_DUTY_SHIFT_SAVE: 'workspace:duty:shift:save',
  WORKSPACE_MEMBER_LIST: 'workspace:member:list',
  WORKSPACE_MEMBER_UPDATE_ROLE: 'workspace:member:updateRole',
  TASK_REVISION_LIST: 'task:revision:list',
  TASK_REVISION_PUBLISH: 'task:revision:publish',
  TASK_REVISION_REVIEW: 'task:revision:review',
  TASK_REVISION_COMPARE: 'task:revision:compare',

  // 股票
  STOCK_DATA: 'stock:data',
  STOCK_INDICATOR_CALC: 'stock:indicator:calc',
  // 以下预留 — 尚未实现
  // STOCK_SUBSCRIBE: 'stock:subscribe',
  // STOCK_UNSUBSCRIBE: 'stock:unsubscribe',

  // 插件
  PLUGIN_LIST: 'plugin:list',
  PLUGIN_INSTALL: 'plugin:install',
  PLUGIN_UNINSTALL: 'plugin:uninstall',
  PLUGIN_ENABLE: 'plugin:enable',
  PLUGIN_DISABLE: 'plugin:disable',
  PLUGIN_PERMISSION_CHECK: 'plugin:permission:check',

  // 应用
  APP_INFO: 'app:info',
  APP_CHECK_UPDATE: 'app:checkUpdate',

  // 浏览器标签页
  BROWSER_CREATE_TAB: 'browser:createTab',
  BROWSER_CLOSE_TAB: 'browser:closeTab',
  BROWSER_LIST_TABS: 'browser:listTabs',
  BROWSER_NAVIGATE: 'browser:navigate',
  BROWSER_GO_BACK: 'browser:goBack',
  BROWSER_GO_FORWARD: 'browser:goForward',
  BROWSER_RELOAD: 'browser:reload',
  INTERVENTION_STATUS: 'intervention:status',
  INTERVENTION_TAKEOVER: 'intervention:takeover',
  INTERVENTION_RESUME: 'intervention:resume',
  INTERVENTION_SCREENSHOT: 'intervention:screenshot',
  INTERVENTION_STEP_INFO: 'intervention:stepInfo',
  RECORDER_START: 'recorder:start',
  RECORDER_STOP: 'recorder:stop',
  RECORDER_ACTION: 'recorder:action',
  TEMPLATE_SAVE: 'template:save',
  TEMPLATE_LIST: 'template:list',
  TEMPLATE_DELETE: 'template:delete',
  TEMPLATE_GOVERNANCE_UPDATE: 'template:governance:update',
  TEMPLATE_BACKFLOW_APPLY: 'template:backflow:apply',
  RESULT_LIST: 'result:list',
  RESULT_DETAIL: 'result:detail',
  RESULT_EXPORT: 'result:export',
  RESULT_MARK_SUSPICIOUS: 'result:markSuspicious',
  RESULT_QUALITY_ANALYZE: 'result:quality:analyze',
  OPS_ACCEPTANCE_METRICS: 'ops:acceptance:metrics',
  HOT_SOURCE_LIST: 'hot:source:list',
  HOT_SOURCE_DETAIL: 'hot:source:detail',
  HOT_SOURCE_CREATE: 'hot:source:create',
  HOT_SOURCE_UPDATE: 'hot:source:update',
  HOT_SOURCE_DELETE: 'hot:source:delete',
  HOT_RUN_LIST: 'hot:run:list',
  HOT_RUN_START: 'hot:run:start',
  HOT_RUN_DETAIL: 'hot:run:detail',
  HOT_REPORT_LIST: 'hot:report:list',
  HOT_REPORT_DETAIL: 'hot:report:detail',
  HOT_REPORT_GENERATE: 'hot:report:generate',
  SESSION_LIST: 'session:list',
  SESSION_CREATE: 'session:create',
  SESSION_DELETE: 'session:delete',
  SESSION_BIND: 'session:bind',
  EXEC_LOG_QUERY: 'execlog:query',
  ALERT_LIST: 'alert:list',
  ALERT_CLAIM: 'alert:claim',
  ALERT_ASSIGN: 'alert:assign',
  ALERT_NOTE: 'alert:note',
  ALERT_ACTION_LIST: 'alert:action:list',
  ALERT_ESCALATE: 'alert:escalate',
  ALERT_CLOSE: 'alert:close',
  ALERT_DISMISS: 'alert:dismiss',
  ALERT_PUSHED: 'alert:pushed',
  REVIEW_LIST: 'review:list',
  REVIEW_CREATE: 'review:create',
  REVIEW_TEMPLATE_BACKFLOW_SUGGEST: 'review:templateBackflow:suggest',
  REVIEW_TEMPLATE_BACKFLOW_DRAFT: 'review:templateBackflow:draft',
  TEMPLATE_LINK_REVIEW: 'template:linkReview',

  // AI 助手
  AI_CHAT: 'ai:chat',
  AI_CONFIG_GET: 'ai:config:get',
  AI_CONFIG_SET: 'ai:config:set',
  AI_TOOLS_LIST: 'ai:tools:list',
  AI_TOOL_EXECUTE: 'ai:tool:execute',
  AI_CONVERSATION_LIST: 'ai:conversation:list',
  AI_CONVERSATION_DELETE: 'ai:conversation:delete',
  AI_MCP_START: 'ai:mcp:start',
  AI_MCP_STOP: 'ai:mcp:stop',
  AI_MCP_STATUS: 'ai:mcp:status',
  AI_MCP_CLIENT_STATUS: 'ai:mcp:client:status',
  AI_MCP_AUDIT_LIST: 'ai:mcp:audit:list',

  // Runner Scheduler
  RUNNER_REGISTRY_LIST: 'runner:registry:list',
  RUNNER_REGISTRY_HEARTBEAT: 'runner:registry:heartbeat',
  RUNNER_REGISTRY_DRAIN: 'runner:registry:drain',
  RUNNER_REGISTRY_RESUME: 'runner:registry:resume',
  RUNNER_QUEUE_LIST: 'runner:queue:list',
  RUNNER_QUEUE_ENQUEUE: 'runner:queue:enqueue',
  RUNNER_QUEUE_CANCEL: 'runner:queue:cancel',
  RUNNER_DISPATCH_TICK: 'runner:dispatch:tick',
  RUNNER_LEASE_LIST: 'runner:lease:list',
  RUNNER_LEASE_RENEW: 'runner:lease:renew',
  RUNNER_LEASE_RELEASE: 'runner:lease:release',
  RUNNER_LEASE_RECONCILE: 'runner:lease:reconcile',

  // Remote Runner 控制面
  REMOTE_RUNNER_CONNECTION_LIST: 'runner:connection:list',
  REMOTE_RUNNER_CONNECTION_SAVE: 'runner:connection:save',
  REMOTE_RUNNER_CONNECTION_DELETE: 'runner:connection:delete',
  REMOTE_RUNNER_CONNECTION_TEST: 'runner:connection:test',
  REMOTE_RUNNER_TASK_LIST: 'runner:task:list',
  REMOTE_RUNNER_TASK_SAVE: 'runner:task:save',
  REMOTE_RUNNER_TASK_DELETE: 'runner:task:delete',
  REMOTE_RUNNER_SESSION_LIST: 'runner:session:list',
  REMOTE_RUNNER_SESSION_SAVE: 'runner:session:save',
  REMOTE_RUNNER_SESSION_DELETE: 'runner:session:delete',
  REMOTE_RUNNER_EXECUTION_START: 'runner:execution:start',
  REMOTE_RUNNER_EXECUTION_GET: 'runner:execution:get',
  REMOTE_RUNNER_EXECUTION_CANCEL: 'runner:execution:cancel',
  REMOTE_RUNNER_EXECUTION_LOGS: 'runner:execution:logs',
  REMOTE_RUNNER_LOG_EVENT: 'runner:log:event',

  // Data Center
  DATA_CENTER_OVERVIEW: 'datacenter:overview',
  DATA_CENTER_RESULTS_LIST: 'datacenter:results:list',
  DATA_CENTER_RESULTS_DETAIL: 'datacenter:results:detail',
  DATA_CENTER_EXPORTS_CREATE: 'datacenter:exports:create',
  DATA_CENTER_EXPORTS_LIST: 'datacenter:exports:list',
  DATA_CENTER_EXPORTS_RETRY: 'datacenter:exports:retry',
  DATA_CENTER_EXPORTS_CANCEL: 'datacenter:exports:cancel',
  DATA_CENTER_DATASETS_LIST: 'datacenter:datasets:list',
  DATA_CENTER_DATASETS_SAVE: 'datacenter:datasets:save',
  DATA_CENTER_WEBHOOKS_LIST: 'datacenter:webhooks:list',
  DATA_CENTER_WEBHOOKS_SAVE: 'datacenter:webhooks:save',
  DATA_CENTER_WEBHOOKS_TEST: 'datacenter:webhooks:test',
  DATA_CENTER_WEBHOOKS_DELETE: 'datacenter:webhooks:delete',
  DATA_CENTER_API_TOKENS_LIST: 'datacenter:apitokens:list',
  DATA_CENTER_API_TOKENS_CREATE: 'datacenter:apitokens:create',
  DATA_CENTER_API_TOKENS_REVOKE: 'datacenter:apitokens:revoke',
  DATA_CENTER_API_STATUS: 'datacenter:api:status',
  DATA_CENTER_API_START: 'datacenter:api:start',
  DATA_CENTER_API_STOP: 'datacenter:api:stop',
  DATA_CENTER_QUALITY_SCAN: 'datacenter:quality:scan',
  DATA_CENTER_QUALITY_SCORE_BATCH: 'datacenter:quality:score:batch',
  DATA_CENTER_QUALITY_INSIGHT_BATCH: 'datacenter:quality:insight:batch',
  DATA_CENTER_QUALITY_RULES_LIST: 'datacenter:quality:rules:list',
  DATA_CENTER_QUALITY_RULES_SAVE: 'datacenter:quality:rules:save',
  DATA_CENTER_EXPORT_UPDATED: 'datacenter:exportupdated',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
